Add missing perl-unicode feature to regex crate
PR #550 reduced the feature flags of the regex crate on only `["std"]`,
however this is not enough, as compiling the used regexps requires the
unicode-perl feature flag to compile the `\s` class (likely to match
Unicode whitespaces).

Without this flag, `prost-build` panicks with the following message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    https?://[^\s)]+
               ^^
error: Unicode-aware Perl class not found (make sure the unicode-perl feature is enabled)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)'
```